/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef FASTMATRIX_PRIVATE_H
#define FASTMATRIX_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.0.2.2"
#define VER_MAJOR	0
#define VER_MINOR	0
#define VER_RELEASE	2
#define VER_BUILD	2
#define COMPANY_NAME	""
#define FILE_VERSION	""
#define FILE_DESCRIPTION	"Developed using the Dev-C++ IDE"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	""

#endif /*FASTMATRIX_PRIVATE_H*/
